// Code generated by "stringer -type=Commodity"; DO NOT EDIT.

package trade

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommodityNone-0]
	_ = x[CommodityFood-1]
	_ = x[CommodityWood-2]
	_ = x[CommodityIronOre-3]
	_ = x[CommodityIron-4]
	_ = x[CommodityTools-5]
}

const _Commodity_name = "CommodityNoneCommodityFoodCommodityWoodCommodityIronOreCommodityIronCommodityTools"

var _Commodity_index = [...]uint8{0, 13, 26, 39, 55, 68, 82}

func (i Commodity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Commodity_index)-1 {
		return "Commodity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Commodity_name[_Commodity_index[idx]:_Commodity_index[idx+1]]
}
